# Generated by Django 5.2.3 on 2025-11-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.IntegerField(blank=True, help_text='Years of experience', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='specialization',
            field=models.CharField(blank=True, choices=[('cardiologist', 'Cardiologist'), ('pediatrician', 'Pediatrician'), ('general', 'General Physician'), ('orthopedic', 'Orthopedic'), ('neurologist', 'Neurologist'), ('dermatologist', 'Dermatologist'), ('psychiatrist', 'Psychiatrist'), ('dentist', 'Dentist')], max_length=50, null=True),
        ),
    ]
