# Generated by Django 5.2.3 on 2025-11-28 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='shared_with',
            field=models.ForeignKey(blank=True, limit_choices_to={'profile__status': 'approved', 'profile__user_type': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DoctorResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription', models.TextField(help_text='Prescription details')),
                ('diagnosis', models.TextField(help_text='Diagnosis details')),
                ('recommendations', models.TextField(help_text='Additional recommendations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(limit_choices_to={'profile__user_type': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_response', to='reports.medicalreport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
