# Generated by Django 5.2.3 on 2025-11-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_medicalreport_shared_with_doctorresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='category',
            field=models.CharField(blank=True, choices=[('cardiologist', 'Cardiology'), ('pediatrician', 'Pediatrics'), ('general', 'General Medicine'), ('orthopedic', 'Orthopedics'), ('neurologist', 'Neurology'), ('dermatologist', 'Dermatology'), ('psychiatrist', 'Psychiatry'), ('dentist', 'Dentistry')], max_length=50, null=True),
        ),
    ]
