# Generated by Django 5.2.3 on 2025-11-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_medicalreport_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorresponse',
            name='advice',
            field=models.TextField(blank=True, help_text='General medical advice'),
        ),
        migrations.AddField(
            model_name='doctorresponse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='doctorresponse',
            name='diagnosis',
            field=models.TextField(help_text='Diagnosis and findings'),
        ),
        migrations.AlterField(
            model_name='doctorresponse',
            name='prescription',
            field=models.TextField(help_text='Prescription details and medications'),
        ),
        migrations.AlterField(
            model_name='doctorresponse',
            name='recommendations',
            field=models.TextField(help_text='Additional recommendations and follow-up instructions'),
        ),
    ]
